title: Unibots 2026

author:
  name: CUR

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Final website detailing the output from our research. Links to individual
  articles written by each person can be found in main body of different sections

# GitHub Pages settings
url: "https://muhie.github.io"
baseurl: "/unibots_jekyll_deployment"

# Build settings

# GitHub Pages uses Minima 2.5.1, so we'll stick with the theme setting
theme: minima

# Comment out remote_theme since we're using the local theme
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md
  - blog.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Remove Minima 3.0+ specific settings for GitHub Pages compatibility
# GitHub Pages uses Minima 2.5.1 which doesn't support these features
#minima:
#  skin: classic
